In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv("weatherHistory.csv")

In [3]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [4]:
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [5]:
df = df.dropna().reset_index(drop=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95936 entries, 0 to 95935
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            95936 non-null  object
 1   Summary                   95936 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           95936 non-null  float64
 4   Apparent Temperature (C)  95936 non-null  float64
 5   Humidity                  95936 non-null  float64
 6   Wind Speed (km/h)         95936 non-null  float64
 7   Wind Bearing (degrees)    95936 non-null  float64
 8   Visibility (km)           95936 non-null  float64
 9   Loud Cover                95936 non-null  float64
 10  Pressure (millibars)      95936 non-null  float64
 11  Daily Summary             95936 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [7]:
del_col = ["Formatted Date", "Summary", "Precip Type", "Loud Cover", "Daily Summary"]
for col in del_col:
    df.drop(col, axis=1, inplace=True)

In [8]:
#Edited Dataset, hedef feature-> Temperature

In [9]:
df.head()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars)
0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,1015.13
1,9.355556,7.227778,0.86,14.2646,259.0,15.8263,1015.63
2,9.377778,9.377778,0.89,3.9284,204.0,14.9569,1015.94
3,8.288889,5.944444,0.83,14.1036,269.0,15.8263,1016.41
4,8.755556,6.977778,0.83,11.0446,259.0,15.8263,1016.51

In [10]:
df.columns

Index(['Temperature (C)', 'Apparent Temperature (C)', 'Humidity',
       'Wind Speed (km/h)', 'Wind Bearing (degrees)', 'Visibility (km)',
       'Pressure (millibars)'],
      dtype='object')

In [11]:
for col in df.columns:
    print(df[col].value_counts())

Temperature (C)
 7.222222     455
 7.777778     407
 12.777778    378
 17.777778    373
 6.111111     369
             ...
-11.694444      1
-8.950000       1
-11.561111      1
-11.977778      1
 30.605556      1
Name: count, Length: 7573, dtype: int64
Apparent Temperature (C)
 12.777778    378
 17.777778    373
 13.888889    342
 17.222222    329
 12.222222    305
             ...
-14.900000      1
-12.961111      1
-13.516667      1
-13.566667      1
 9.233333       1
Name: count, Length: 8984, dtype: int64
Humidity
0.93    5699
0.92    3878
0.96    3834
1.00    2888
0.89    2829
        ...
0.15      10
0.16       8
0.14       4
0.13       1
0.12       1
Name: count, Length: 90, dtype: int64
Wind Speed (km/h)
3.2200     2441
11.2700    1493
6.4400     1356
0.0000     1297
8.0500      920
           ...
38.9942       1
34.7599       1
41.1999       1
39.8314       1
38.5273       1
Name: count, Length: 2484, dtype: int64
Wind Bearing (degrees)
0.0      2262
150.0    1795
160.0    1630
140.0    1507
310.0    1450
         ...
65.0       52
83.0       48
95.0       47
86.0       47
94.0       44
Name: count, Length: 360, dtype: int64
Visibility (km)
9.9820     18213
16.1000     7034
15.8263     5664
11.2700     4579
10.3523     3529
           ...
13.0410        1
13.0732        1
14.0070        1
12.5741        1
16.0839        1
Name: count, Length: 949, dtype: int64
Pressure (millibars)
0.00       1288
1017.70     123
1015.00     119
1015.80     118
1019.10     117
           ...
999.42        1
1040.63       1
999.83        1
1041.24       1
997.59        1
Name: count, Length: 4971, dtype: int64

In [12]:
for col in df.columns:
    print(col)
    print(df[col].unique())

Temperature (C)
[ 9.47222222  9.35555556  9.37777778 ... 28.47222222 28.33888889
 30.60555556]
Apparent Temperature (C)
[ 7.38888889  7.22777778  9.37777778 ... 12.14444444  9.73888889
  9.23333333]
Humidity
[0.89 0.86 0.83 0.85 0.95 0.82 0.72 0.67 0.54 0.55 0.51 0.47 0.46 0.6
 0.63 0.69 0.7  0.77 0.76 0.79 0.62 0.66 0.8  0.78 0.61 0.52 0.4  0.37
 0.36 0.43 0.5  0.53 0.58 0.59 0.87 0.93 0.84 0.73 0.71 0.74 0.81 0.9
 0.99 0.96 0.75 0.88 0.65 0.91 0.94 0.92 0.44 0.56 0.68 0.64 0.48 0.57
 0.98 1.   0.38 0.41 0.45 0.49 0.32 0.42 0.35 0.39 0.97 0.34 0.33 0.31
 0.3  0.29 0.27 0.28 0.26 0.24 0.25 0.23 0.19 0.17 0.2  0.15 0.18 0.22
 0.14 0.21 0.16 0.13 0.   0.12]
Wind Speed (km/h)
[14.1197 14.2646  3.9284 ... 37.0622 35.5971 30.751 ]
Wind Bearing (degrees)
[251. 259. 204. 269. 258. 260. 279. 290. 316. 281. 289. 262. 288. 230.
 163. 139. 147. 160. 152. 150. 149. 180. 161. 135. 141. 151. 169. 170.
 187. 179. 162. 159. 168.  32. 140. 103. 113. 129. 207. 153.   4. 341.
  15. 348. 321. 311. 339. 340. 330.  19. 277.   9.   0. 350. 349. 338.
 320. 310. 328.  20.  28.  11. 326. 309. 193. 273. 300. 307. 319. 318.
 243. 177. 172. 142. 130. 359. 166. 145. 178. 223. 240. 231. 214. 222.
 241. 235. 238. 211. 221. 215. 224. 358.   8.  59.  63.  65. 146. 305.
 327. 271. 297. 301. 308. 272. 351. 175. 138. 158. 132. 209. 250. 295.
 280. 270. 239. 242. 266. 278. 325. 282. 274. 255.  46. 284. 283. 313.
 345.  16. 332.  12.  39.   3.  33.  24.  25.  31.  47.  67.  60. 144.
  57.   2.  18.  48.  29. 335. 228. 315.  40. 143. 133. 136. 355. 123.
 199. 227. 156. 261. 357. 190. 298.  10. 127.  81. 120. 134. 115. 347.
  72.   7.   1.  30. 352. 353.  85.  49.  21.  23.  35.  56. 337. 285.
 306.   6. 116. 197. 275. 100. 333. 304.  90.  58. 157. 329. 268. 317.
 210. 226. 188. 292. 154. 205. 181. 185. 148.  68. 155. 137.  95.  50.
  80.  83.  73.  70. 106.  94. 117.  53.  82. 101. 102.  54.  52.  38.
 128. 164.  71. 108. 121. 122. 189. 246. 302. 245. 291. 312. 296. 264.
  41.  62. 119.  98. 124. 299. 173. 176. 194. 171. 183. 167. 229. 303.
 212. 322. 331. 342. 324. 265. 267. 165. 236. 110. 216. 218. 354.  75.
 186. 249.  55.  64.  17.   5. 263. 256.  69.  89. 200. 112. 192. 287.
 237. 213. 220. 217. 202. 208. 198. 201. 111. 104. 126. 191. 254. 107.
 118. 131. 232. 196. 174. 248. 182. 294. 252. 247. 233. 244. 276. 225.
 234. 219.  84.  96. 336. 253. 346. 314. 203.  13. 343. 125.  61.  79.
  93. 286.  27. 323. 195.  87. 105. 206.  44.  51.  36.  43.  26.  74.
 109. 356. 334.  99.  88. 257. 293.  45. 344. 184.  22.  42.  37.  14.
  34.  76.  91.  86.  97.  66. 114.  77.  92.  78.]
Visibility (km)
[1.58263e+01 1.49569e+01 9.98200e+00 1.12056e+01 1.14471e+01 1.12700e+01
 1.10285e+01 6.19850e+00 8.05000e+00 1.03523e+01 6.69760e+00 9.90150e+00
 5.97310e+00 1.08031e+01 1.06743e+01 1.08192e+01 1.07548e+01 1.08997e+01
 1.08514e+01 1.10768e+01 1.08836e+01 7.61530e+00 2.65650e+00 3.81570e+00
 4.49190e+00 4.44360e+00 5.68330e+00 3.10730e+00 3.20390e+00 1.40553e+01
 6.11800e+00 6.16630e+00 7.96950e+00 6.34340e+00 1.05455e+01 1.49086e+01
 1.50052e+01 1.58746e+01 1.00464e+01 1.00303e+01 1.19784e+01 1.41680e+01
 5.92480e+00 1.22360e+00 7.21280e+00 1.11251e+01 1.33791e+01 1.13988e+01
 1.12861e+01 1.56975e+01 1.48764e+01 6.84250e+00 1.53594e+01 4.29870e+00
 4.12160e+00 4.76560e+00 2.93020e+00 5.84430e+00 9.61170e+00 9.67610e+00
 2.01250e+00 5.21640e+00 1.45866e+01 1.56009e+01 1.47154e+01 6.11800e-01
 3.63860e+00 1.11090e+00 5.15200e-01 4.34700e-01 6.92300e-01 2.20570e+00
 4.20210e+00 6.31120e+00 8.19490e+00 6.89080e+00 7.27720e+00 4.74950e+00
 5.82820e+00 3.83180e+00 4.50800e+00 3.12340e+00 1.80320e+00 3.88010e+00
 3.86400e+00 3.25220e+00 6.44000e-01 1.25580e+00 2.35060e+00 4.02500e+00
 6.26290e+00 9.62780e+00 8.13050e+00 1.06260e+00 1.78710e+00 3.36490e+00
 4.45970e+00 1.91590e+00 1.75490e+00 2.36670e+00 2.89800e-01 2.55990e+00
 6.29510e+00 1.11412e+01 1.48120e+01 9.80490e+00 2.02860e+00 1.73880e+00
 7.88900e-01 9.54730e+00 4.28260e+00 7.40600e-01 8.33980e+00 1.40875e+01
 1.54721e+01 1.09802e+01 1.04006e+01 1.19301e+01 1.20428e+01 1.52628e+01
 1.18979e+01 1.16886e+01 9.75660e+00 9.43460e+00 1.46349e+01 1.16725e+01
 9.69220e+00 4.66900e-01 5.39350e+00 9.53120e+00 1.53111e+01 3.44540e+00
 1.09480e+01 1.00625e+01 2.73700e+00 1.57297e+01 3.97670e+00 3.67080e+00
 3.75130e+00 7.14840e+00 7.90510e+00 9.94980e+00 1.04167e+01 7.37380e+00
 1.10446e+01 9.01600e+00 1.39104e+01 1.56492e+01 1.47315e+01 1.36528e+01
 4.58850e+00 5.87650e+00 1.12539e+01 5.03930e+00 6.98740e+00 1.40231e+01
 1.02718e+01 1.38943e+01 9.70830e+00 9.98200e-01 9.85320e+00 1.54399e+01
 1.42324e+01 3.91230e+00 1.55526e+01 7.82460e+00 4.94270e+00 6.93910e+00
 1.04811e+01 6.53660e+00 1.36850e+01 6.06970e+00 6.58490e+00 4.99100e+00
 1.60517e+01 7.13230e+00 9.83710e+00 1.39426e+01 1.61000e+01 1.13183e+01
 6.02140e+00 4.62070e+00 1.47637e+01 1.07870e+01 3.49370e+00 1.01913e+01
 8.30760e+00 1.47959e+01 7.87290e+00 1.04489e+01 7.98560e+00 8.00170e+00
 1.05294e+01 1.07226e+01 1.37333e+01 8.42030e+00 8.11440e+00 1.17047e+01
 7.03570e+00 4.39530e+00 4.34700e+00 4.33090e+00 2.89800e+00 1.89980e+00
 4.18600e-01 2.97850e+00 5.32910e+00 4.84610e+00 4.83000e+00 4.00890e+00
 3.94450e+00 3.30050e+00 1.18496e+01 9.48290e+00 1.70660e+00 1.36850e+00
 6.72980e+00 1.62610e+00 3.01070e+00 4.91050e+00 5.76380e+00 7.56700e-01
 3.22000e-01 1.61000e-01 6.60100e-01 2.73700e-01 2.09300e-01 9.33800e-01
 9.66000e-01 1.30410e+00 1.81930e+00 2.57600e+00 2.44720e+00 1.72270e+00
 1.88370e+00 4.83000e-01 3.05900e-01 1.77100e-01 6.27900e-01 7.08400e-01
 2.60820e+00 2.54380e+00 1.32020e+00 8.53300e-01 4.02500e-01 2.41500e-01
 1.93200e-01 1.61000e-02 6.76200e-01 5.47400e-01 0.00000e+00 4.83000e-02
 3.22000e-02 3.38100e-01 8.05000e-01 7.24500e-01 1.64220e+00 1.12700e-01
 1.27190e+00 1.41680e+00 8.85500e-01 1.28800e+00 1.44900e+00 2.52770e+00
 2.83360e+00 1.06582e+01 1.57780e+00 3.41320e+00 3.92840e+00 5.52230e+00
 4.87830e+00 4.26650e+00 6.00530e+00 6.24680e+00 6.48830e+00 1.38138e+01
 6.35950e+00 5.13590e+00 5.28080e+00 1.15920e+00 6.05360e+00 7.74410e+00
 5.40960e+00 4.81390e+00 1.02557e+01 1.94810e+00 9.82100e-01 8.46860e+00
 7.63140e+00 3.39710e+00 3.13950e+00 4.52410e+00 7.72800e+00 3.78350e+00
 4.31480e+00 4.37920e+00 4.04110e+00 3.55810e+00 4.57240e+00 7.51870e+00
 8.61350e+00 7.05180e+00 1.56170e+00 3.05900e+00 5.69940e+00 6.03750e+00
 4.41140e+00 1.93200e+00 5.66720e+00 6.18240e+00 1.77100e+00 2.15740e+00
 2.62430e+00 3.50980e+00 5.47400e+00 8.75840e+00 1.39748e+01 1.15276e+01
 8.17880e+00 6.77810e+00 4.07330e+00 8.96770e+00 1.51501e+01 1.42163e+01
 1.20911e+01 1.45222e+01 8.14660e+00 1.38460e+00 3.86400e-01 1.85150e+00
 1.86760e+00 2.59210e+00 1.51340e+00 3.09120e+00 3.96060e+00 5.57060e+00
 3.42930e+00 3.33270e+00 1.25902e+01 8.05000e-02 1.59390e+00 5.89260e+00
 7.18060e+00 9.11260e+00 2.96240e+00 5.81210e+00 4.89440e+00 4.95880e+00
 5.79600e+00 5.50620e+00 2.72090e+00 7.69580e+00 9.56340e+00 5.60280e+00
 4.36310e+00 4.73340e+00 5.95700e+00 1.49730e+00 1.35240e+00 2.14130e+00
 5.11980e+00 1.36206e+01 7.64750e+00 1.46510e+00 1.65830e+00 2.86580e+00
 4.08940e+00 4.42750e+00 4.18600e+00 2.88190e+00 8.32370e+00 1.23970e+00
 1.17530e+00 2.46330e+00 7.06790e+00 1.27190e+01 9.78880e+00 8.09830e+00
 9.57950e+00 9.27360e+00 7.77630e+00 9.64390e+00 8.54910e+00 7.71190e+00
 6.79420e+00 6.82640e+00 6.85860e+00 8.22710e+00 1.15759e+01 6.90690e+00
 7.35770e+00 3.89620e+00 3.52590e+00 5.65110e+00 8.74230e+00 4.68510e+00
 4.79780e+00 3.84790e+00 1.14310e+00 8.37200e-01 9.17700e-01 9.01600e-01
 9.49900e-01 5.53840e+00 5.73160e+00 6.13410e+00 1.44095e+01 9.45070e+00
 6.64930e+00 9.82100e+00 1.05938e+01 3.71910e+00 6.87470e+00 1.44900e-01
 3.46150e+00 4.05720e+00 9.59560e+00 1.83540e+00 2.75310e+00 3.34880e+00
 3.18780e+00 3.04290e+00 1.43612e+01 7.72800e-01 5.63500e-01 4.78170e+00
 1.07709e+01 1.46832e+01 1.01108e+01 9.74050e+00 2.99460e+00 3.07510e+00
 3.17170e+00 1.61000e+00 8.21100e-01 3.15560e+00 4.15380e+00 6.47220e+00
 1.46027e+01 4.50800e-01 1.29605e+01 1.04972e+01 7.00350e+00 1.11895e+01
 3.47760e+00 6.23070e+00 5.10370e+00 7.80850e+00 1.07387e+01 8.08220e+00
 1.44739e+01 5.90870e+00 1.10607e+01 9.19310e+00 9.32190e+00 4.71730e+00
 3.65470e+00 3.57420e+00 5.31300e+00 2.10910e+00 1.05777e+01 7.26110e+00
 1.55365e+01 2.07690e+00 2.17350e+00 1.28961e+01 1.53755e+01 1.09480e+00
 4.23430e+00 2.12520e+00 3.62250e+00 1.09158e+01 4.60460e+00 6.40780e+00
 7.11620e+00 7.08400e+00 6.08580e+00 3.76740e+00 4.92660e+00 2.30230e+00
 6.74590e+00 5.07150e+00 5.08760e+00 2.38280e+00 2.49550e+00 2.94630e+00
 2.33450e+00 5.86040e+00 7.55090e+00 7.66360e+00 8.64570e+00 1.54560e+00
 9.41850e+00 9.86930e+00 5.26470e+00 5.23250e+00 9.14480e+00 5.34520e+00
 4.47580e+00 8.91940e+00 9.49900e+00 1.12378e+01 8.71010e+00 5.24860e+00
 1.16081e+01 8.93550e+00 1.18013e+01 1.29283e+01 1.41036e+01 9.40240e+00
 1.03684e+01 1.08353e+01 4.21820e+00 9.51510e+00 1.17530e+01 7.88900e+00
 9.28970e+00 9.93370e+00 7.59920e+00 3.28440e+00 3.26830e+00 5.18420e+00
 2.47940e+00 3.60640e+00 2.68870e+00 4.66900e+00 5.74770e+00 3.23610e+00
 3.22000e+00 1.01430e+00 1.15920e+01 1.24292e+01 1.09641e+01 8.35590e+00
 1.44256e+01 1.03845e+01 1.11573e+01 1.02074e+01 1.52467e+01 8.25930e+00
 1.45705e+01 1.48442e+01 1.13505e+01 3.70300e+00 1.44578e+01 2.31840e+00
 2.06080e+00 1.33147e+01 8.62960e+00 5.42570e+00 7.53480e+00 5.44180e+00
 7.42210e+00 6.15020e+00 2.41500e+00 9.37020e+00 3.54200e-01 2.81750e+00
 4.70120e+00 4.55630e+00 1.00947e+01 8.90330e+00 7.29330e+00 2.64040e+00
 1.06421e+01 8.51690e+00 9.38630e+00 9.24140e+00 1.10929e+01 5.16810e+00
 7.16450e+00 8.01780e+00 2.91410e+00 1.43290e+00 7.93730e+00 5.95700e-01
 2.27010e+00 7.45430e+00 1.44900e+01 8.85500e+00 1.01752e+01 1.55043e+01
 1.54560e+01 1.54238e+01 5.02320e+00 9.66000e+00 4.25040e+00 1.34435e+01
 1.34757e+01 1.07065e+01 1.04650e+00 1.43451e+01 1.15437e+01 1.55204e+01
 4.54020e+00 1.14954e+01 1.51179e+01 1.56653e+01 1.50535e+01 9.17700e+00
 5.77990e+00 7.79240e+00 9.06430e+00 6.60100e+00 6.52050e+00 6.10190e+00
 6.45610e+00 7.30940e+00 2.18960e+00 2.84970e+00 9.12870e+00 7.67970e+00
 1.40070e+00 7.40600e+00 1.69050e+00 3.59030e+00 3.54200e+00 5.58670e+00
 5.31300e-01 1.52950e+00 1.30893e+01 1.98030e+00 1.39587e+01 1.19140e+01
 8.06610e+00 9.35410e+00 9.33800e+00 1.16403e+01 1.03040e+01 7.01960e+00
 1.35401e+01 1.53916e+01 1.54077e+01 1.43290e+01 3.73520e+00 6.21460e+00
 4.16990e+00 8.16270e+00 5.15200e+00 7.56700e+00 9.20920e+00 9.09650e+00
 6.61710e+00 1.67440e+00 1.56814e+01 1.43934e+01 1.15115e+01 1.21877e+01
 1.49730e+01 1.57136e+01 1.52789e+01 1.59068e+01 8.82280e+00 2.28620e+00
 5.20030e+00 1.32664e+01 7.38990e+00 1.12700e+00 2.22180e+00 1.13827e+01
 6.63320e+00 2.04470e+00 3.70300e-01 4.99100e-01 2.09300e+00 5.36130e+00
 1.96420e+00 2.78530e+00 2.23790e+00 2.67260e+00 3.79960e+00 2.80140e+00
 2.51160e+00 5.45790e+00 3.99280e+00 2.70480e+00 3.02680e+00 5.98920e+00
 2.76920e+00 1.48120e+00 1.13666e+01 7.19670e+00 7.95340e+00 7.48650e+00
 2.25400e+00 1.38621e+01 9.16090e+00 1.01591e+01 9.66000e-02 7.32550e+00
 5.61890e+00 9.99810e+00 1.01430e+01 6.92300e+00 1.14149e+01 8.87110e+00
 1.44417e+01 5.29690e+00 2.43110e+00 1.22682e+01 1.24775e+01 8.67790e+00
 9.46680e+00 1.17369e+01 1.03362e+01 4.63680e+00 4.13770e+00 5.00710e+00
 9.77270e+00 7.43820e+00 5.55450e+00 1.46671e+01 1.45383e+01 7.34160e+00
 4.86220e+00 6.66540e+00 1.99640e+00 8.88720e+00 9.25750e+00 8.59740e+00
 1.02396e+01 1.33630e+01 1.35240e+01 1.41841e+01 2.25400e-01 7.85680e+00
 5.63500e+00 1.42807e+01 1.39265e+01 1.16242e+01 1.06904e+01 6.95520e+00
 2.57600e-01 1.20750e+00 9.72440e+00 8.83890e+00 6.97130e+00 1.54882e+01
 1.14632e+01 1.11734e+01 9.30580e+00 4.10550e+00 1.55687e+01 1.21555e+01
 1.22843e+01 1.25097e+01 1.26063e+01 1.37494e+01 1.38460e+01 9.88540e+00
 8.77450e+00 1.58424e+01 6.71370e+00 8.37200e+00 1.47798e+01 4.65290e+00
 3.68690e+00 1.19140e+00 1.32503e+01 1.28478e+01 7.58310e+00 8.03390e+00
 1.10124e+01 6.50440e+00 1.31537e+01 1.13022e+01 8.66180e+00 1.07870e+00
 1.46510e+01 7.50260e+00 1.37816e+01 5.79600e-01 1.51340e+01 1.27029e+01
 1.26868e+01 1.18818e+01 1.13344e+01 1.36367e+01 1.02235e+01 8.69400e+00
 1.20106e+01 1.51823e+01 1.20750e+01 1.31376e+01 1.32342e+01 7.92120e+00
 1.19945e+01 1.31698e+01 6.44000e-02 1.05616e+01 1.09319e+01 7.84070e+00
 8.58130e+00 9.08040e+00 1.33630e+00 1.04650e+01 3.31660e+00 9.04820e+00
 1.15598e+01 1.02879e+01 1.05133e+01 7.10010e+00 1.21233e+01 1.38299e+01
 1.00142e+01 7.22890e+00 6.76200e+00 1.34113e+01 8.79060e+00 1.29927e+01
 8.99990e+00 1.03040e+00 1.46188e+01 1.42968e+01 1.03201e+01 1.30088e+01
 8.72620e+00 5.49010e+00 1.18335e+01 1.42002e+01 1.17852e+01 1.11090e+01
 1.06099e+01 6.39170e+00 6.37560e+00 1.25580e+01 1.41519e+01 1.51662e+01
 1.22199e+01 5.05540e+00 6.68150e+00 6.81030e+00 6.42390e+00 5.37740e+00
 1.36689e+01 7.24500e+00 1.43129e+01 6.44000e+00 6.32730e+00 3.38100e+00
 6.55270e+00 1.38782e+01 8.24320e+00 1.24614e+01 1.40714e+01 2.39890e+00
 1.35562e+01 1.21394e+01 1.52145e+01 4.97490e+00 8.69400e-01 1.34918e+01
 8.95160e+00 9.03210e+00 1.14310e+01 7.76020e+00 1.00786e+01 5.94090e+00
 8.38810e+00 1.34274e+01 1.37977e+01 6.27900e+00 1.09963e+01 1.31215e+01
 8.21100e+00 9.96590e+00 1.04328e+01 1.26707e+01 1.46993e+01 1.37655e+01
 1.42485e+01 8.43640e+00 1.43773e+01 1.30249e+01 1.28317e+01 1.48603e+01
 1.32020e+01 8.29150e+00 1.59229e+01 8.98380e+00 1.28800e-01 1.22521e+01
 1.50213e+01 1.28156e+01 1.45061e+01 1.12217e+01 1.57780e+01 1.57941e+01
 1.53433e+01 1.42646e+01 6.56880e+00 1.48281e+01 1.40392e+01 1.41358e+01
 1.59551e+01 1.17691e+01 1.49891e+01 1.58585e+01 1.51984e+01 1.50857e+01
 1.23809e+01 1.19623e+01 1.27673e+01 1.21716e+01 1.26385e+01 1.18174e+01
 1.30410e+01 1.30732e+01 1.40070e+01 8.27540e+00 1.25741e+01 1.56170e+01
 1.60195e+01 1.45544e+01 1.22360e+01 1.23970e+01 8.56520e+00 1.24936e+01
 1.25419e+01 9.22530e+00 7.47040e+00 1.31859e+01 8.50080e+00 1.35723e+01
 1.39909e+01 1.41197e+01 1.34596e+01 1.01269e+01 8.45250e+00 8.48470e+00
 8.40420e+00 8.53300e+00 9.91760e+00 5.71550e+00 8.80670e+00 1.14793e+01
 1.06260e+01 1.24131e+01 1.08675e+01 1.23326e+01 1.17208e+01 1.52306e+01
 1.52950e+01 1.53272e+01 1.57619e+01 1.58102e+01 1.59390e+01 1.59873e+01
 1.60839e+01]
Pressure (millibars)
[1015.13 1015.63 1015.94 ...  998.11  998.52  997.59]

In [13]:
#sns.heatmap(df.corr(), annot=True)

In [14]:
X = df.drop("Temperature (C)", axis=1)
y = df["Temperature (C)"]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=15)

In [17]:
X_train.corr()

,Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars)
Apparent Temperature (C),1.000000,-0.603619,-0.057925,0.028892,0.382184,0.001402
Humidity,-0.603619,1.000000,-0.222124,-0.000277,-0.369563,0.004659
Wind Speed (km/h),-0.057925,-0.222124,1.000000,0.103085,0.101343,-0.050108
Wind Bearing (degrees),0.028892,-0.000277,0.103085,1.000000,0.047330,-0.012278
Visibility (km),0.382184,-0.369563,0.101343,0.047330,1.000000,0.063837
Pressure (millibars),0.001402,0.004659,-0.050108,-0.012278,0.063837,1.000000

In [18]:
X_train.shape

(67155, 6)

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
from sklearn.tree import DecisionTreeRegressor

In [21]:
tree_model_regressor = DecisionTreeRegressor(criterion="squared_error", splitter="best")

In [22]:
tree_model_regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [24]:
y_pred = tree_model_regressor.predict(X_test)
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

Mean Squared Error: 0.0086297608890639
Mean Absolute Error: 0.02407259418829813
R2 Score: 0.9999061666081014

In [25]:
#hyperparameter tuning

In [26]:
params = {
    "criterion": ["squared_error"],
    "max_depth": [5,15,None],
    "max_features": ["sqrt", "log2", None],
    "min_samples_split": [2,5,10],
}

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
dtr = DecisionTreeRegressor()

In [32]:
rscv = RandomizedSearchCV(estimator= dtr , param_distributions=params, cv=5, n_jobs=-1)

In [33]:
#rscv.fit(X_train, y_train)
#y_pred = rscv.predict(X_test)
#mae = mean_absolute_error(y_test, y_pred)
#score = r2_score(y_test, y_pred)